# Generated by Django 2.2 on 2020-06-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar_rate', models.FloatField(verbose_name='Курс Доллара')),
                ('dollar_volatility', models.FloatField(verbose_name='Изменение курса Доллара')),
                ('euro_rate', models.FloatField(verbose_name='Курс Евро')),
                ('euro_volatility', models.FloatField(verbose_name='Изменение курса Евро')),
                ('relevance', models.DateTimeField(auto_now_add=True, verbose_name='Актуальность')),
            ],
            options={
                'db_table': 'bm_exchange_rate',
                'ordering': ['-relevance'],
            },
        ),
    ]
