# Generated by Django 2.2 on 2020-06-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerates',
            name='id',
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='relevance',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Актуальность'),
        ),
    ]
