# Generated by Django 2.2 on 2020-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200613_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyWarnings',
            fields=[
                ('pub_date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок сообщения')),
                ('link', models.CharField(max_length=1000, verbose_name='Ссылка на первоисточник')),
                ('full_text', models.CharField(max_length=4000, verbose_name='Текст сообщения')),
                ('enc_link', models.CharField(max_length=2000, verbose_name='Ссылка на вложение')),
                ('enc_length', models.IntegerField(verbose_name='Размер вложения')),
                ('enc_type', models.CharField(max_length=50, verbose_name='Тип вложение')),
            ],
            options={
                'db_table': 'bm_emergency_warnings',
                'ordering': ['-pub_date'],
            },
        ),
    ]
