# Generated by Django 2.2 on 2020-06-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_emergencywarnings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencywarnings',
            name='enc_length',
            field=models.IntegerField(default=0, verbose_name='Размер вложения'),
        ),
        migrations.AlterField(
            model_name='emergencywarnings',
            name='enc_link',
            field=models.CharField(max_length=2000, null=True, verbose_name='Ссылка на вложение'),
        ),
        migrations.AlterField(
            model_name='emergencywarnings',
            name='enc_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип вложение'),
        ),
    ]
