# Generated by Django 2.2 on 2020-06-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200613_2303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyWarnings',
        ),
    ]
