# Generated by Django 2.2 on 2020-06-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_delete_emergencywarnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyWarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(unique=True, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок сообщения')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='Описание')),
                ('source_link', models.CharField(max_length=1000, verbose_name='Ссылка на первоисточник')),
                ('full_text', models.CharField(max_length=4000, verbose_name='Текст сообщения')),
                ('enc_link', models.CharField(max_length=2000, null=True, verbose_name='Ссылка на вложение')),
                ('enc_length', models.IntegerField(default=0, verbose_name='Размер вложения')),
                ('enc_type', models.CharField(max_length=50, null=True, verbose_name='Тип вложение')),
            ],
            options={
                'verbose_name': 'Предупреждения МЧС',
                'db_table': 'bm_emergency_warnings',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='exchangerates',
            options={'ordering': ['-relevance'], 'verbose_name': 'Курсы валют'},
        ),
    ]
