# Generated by Django 2.2 on 2020-06-25 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_emergencywarnings_imported_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencywarnings',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Предупреждения МЧС г.Москвы'},
        ),
        migrations.AlterModelOptions(
            name='exchangerates',
            options={'ordering': ['-rate_date', 'currency', '-imported_at'], 'verbose_name': 'Курсы валют'},
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='currency',
            field=models.CharField(default='', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время импорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='rate',
            field=models.FloatField(default=0, verbose_name='Курс валюты'),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='rate_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата курса'),
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='rate_volatility',
            field=models.FloatField(default=0, verbose_name='Изменение курса'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerates',
            unique_together={('currency', 'rate', 'rate_date')},
        ),
        migrations.RemoveField(
            model_name='exchangerates',
            name='dollar_rate',
        ),
        migrations.RemoveField(
            model_name='exchangerates',
            name='dollar_volatility',
        ),
        migrations.RemoveField(
            model_name='exchangerates',
            name='euro_rate',
        ),
        migrations.RemoveField(
            model_name='exchangerates',
            name='euro_volatility',
        ),
        migrations.RemoveField(
            model_name='exchangerates',
            name='relevance',
        ),
    ]
