# Generated by Django 2.2 on 2020-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200625_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=100, verbose_name='Источник')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('image', models.CharField(max_length=1000, verbose_name='Ссылка на заглавное изображение')),
                ('url', models.CharField(max_length=1000, verbose_name='Ссылка на источник')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время создания на источнике')),
                ('last_modified', models.DateTimeField(verbose_name='Дата и время изменения на источнике')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время импорта')),
                ('views', models.BigIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
        ),
    ]
