# Generated by Django 2.2 on 2020-06-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости'},
        ),
        migrations.AlterModelTable(
            name='news',
            table='bm_news',
        ),
    ]
