# Generated by Django 2.2 on 2020-06-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200626_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
    ]
