# Generated by Django 2.2 on 2020-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_news_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(default='', max_length=100, verbose_name='Источник'),
        ),
    ]
