# Generated by Django 2.2 on 2020-06-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_news_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
