# Generated by Django 2.2 on 2020-06-28 13:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dirty_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Грязные данные с источника'),
        ),
    ]
