# Generated by Django 2.2 on 2020-06-28 13:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_news_dirty_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dirty_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Грязные данные с источника'),
        ),
    ]
