# Generated by Django 2.2 on 2020-06-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20200628_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ссылка на заглавное изображение'),
        ),
    ]
