# Generated by Django 2.2 on 2020-06-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_news_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-last_modified'], 'verbose_name': 'Новости'},
        ),
    ]
