# Generated by Django 2.2 on 2020-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20200628_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPredictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=250, verbose_name='Текст предсказания')),
            ],
        ),
    ]
