# Generated by Django 2.2 on 2020-07-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_dailypredictions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypredictions',
            options={'verbose_name': 'Ежедневные короткие предсказания'},
        ),
        migrations.AlterModelTable(
            name='dailypredictions',
            table='bm_daily_predictions',
        ),
    ]
