# Generated by Django 2.2 on 2020-07-12 18:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_localyandex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitesDataCaches',
            fields=[
                ('source', models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='Источник')),
                ('dirty_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Грязные данные от источника')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время импорта')),
            ],
            options={
                'verbose_name': 'Кэшированные данные с сайтов-источников',
                'db_table': 'bm_sites_data_caches',
            },
        ),
        migrations.DeleteModel(
            name='LocalYandex',
        ),
    ]
