# Generated by Django 2.2 on 2020-07-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20200712_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesdatacaches',
            name='imported_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время импорта'),
        ),
    ]
